In [2]:
import numpy as np

In [5]:
a=np.array([1,5,8,7])
a

array([1, 5, 8, 7])

In [6]:
#implicit conversion - if array has a float element,it converts all elements in a float
b=np.array([1,5,7,3.4])
b

array([1. , 5. , 7. , 3.4])

In [7]:
#arange method - it works exactly same as range function.
c =np.arange(11)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
c=np.arange(10,21,2)
c

array([10, 12, 14, 16, 18, 20])

In [9]:
#memory management-  we can assign datatype according to our preference
d=np.array([1,3,5,6], dtype=np.int8)
d

array([1, 3, 5, 6], dtype=int8)

In [18]:
#create array using linspace method -  it creates an array of same equidistant elements.
e= np.linspace(10,20,5)  #(start,end(inclusive),count_of_no)
e

array([10. , 12.5, 15. , 17.5, 20. ])

In [11]:
#attributes

a.ndim # it tells the dimension of an array


1

In [12]:
#2d array
A= np.array([[1,3,5,8],[3,5,8,9],[4,2,7,5]])
A

array([[1, 3, 5, 8],
       [3, 5, 8, 9],
       [4, 2, 7, 5]])

In [13]:
A.shape #it tells the shape of an array like how much row and column it contains an array

(3, 4)

**2D array using methods**

In [14]:
#ones- it creates a matrices of 1s
b=np.ones([3,2])
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
#zeros method - it creates a matrices of 0s
c= np.zeros([4,3])
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
#eye method (also known as identity matrix)
c = np.eye(4,2)
c

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [17]:
#diag method
g= np.diag([1,2,4,6])
g



array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [ ]:
np.diag(g)

In [19]:
#3D model
a= np.array([[[312,322,333],[311,312,312],[323,432,322]],[[122,123,124],[125,126,127],[127,128,129]],[[312,313,314],[315,316,317],[321,324,325]]])

In [20]:
a

array([[[312, 322, 333],
        [311, 312, 312],
        [323, 432, 322]],

       [[122, 123, 124],
        [125, 126, 127],
        [127, 128, 129]],

       [[312, 313, 314],
        [315, 316, 317],
        [321, 324, 325]]])

In [21]:
#create random array using methods
#rand

a=np.random.rand(5)
a

array([0.84001426, 0.52150557, 0.16103747, 0.29380238, 0.55032897])

In [22]:
b=np.random.randn(4)
b

array([-0.49547489,  0.83772135,  0.84266129,  0.68428446])

In [24]:
n= np.array([1,2,4,6],dtype=float)
n.dtype
n

array([1., 2., 4., 6.])

In [23]:
c=np.array([1+2j, 4+3j] )
c.dtype
c

array([1.+2.j, 4.+3.j])

In [25]:
d=np.array([[True,False],[True,False]])
d.dtype

dtype('bool')

In [26]:
#indexing array
a= np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [27]:
a[-1]

19

In [28]:
b=np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
b[2,2]

1.0

In [30]:
#assignment
b[1,0]=7
b

array([[1., 0., 0.],
       [7., 1., 0.],
       [0., 0., 1.]])

In [31]:
#slicing array
a[2:5]

array([12, 13, 14])

In [32]:
#shares_memory & copy method

a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
b=a[::2]   # b is a view array of a so it also does affect the actual array by any kind of manipulation
b[2]=34


In [35]:
a

array([10, 11, 12, 13, 34, 15, 16, 17, 18, 19])

In [36]:
np.shares_memory(a,b)

True

In [37]:
#to avoid this situation where we don't want that actual array gets manipulated via view array, we use copy()
b=a[::3].copy()

In [38]:
b
np.shares_memory(a,b)

False

In [39]:
#boolean indexing
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
mask= (a%2!=0)
a[mask]  #mask is a boolean array i.e. it contains only True and False... our answer will be all the value which has corresponding true

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [41]:
#integer indexing- arrays can also be indexed using integer arrays
r= np.random.randint(20,50,10)
r


array([47, 20, 37, 49, 41, 23, 30, 36, 24, 24])

In [42]:
#integer indexing
r[[1,3,7]]

array([20, 49, 36])

In [43]:
#addition,subtraction,multiplication
a=np.array([2,4,8,5])
#a+1
#a*2
a/2

array([1. , 2. , 4. , 2.5])

In [44]:
b=np.array([3,6,5,1])
a+b

array([ 5, 10, 13,  6])

In [45]:
#sin,log,exp
np.sin(b)
np.log(b)
np.exp(b)

array([ 20.08553692, 403.42879349, 148.4131591 ,   2.71828183])

In [46]:
#element wise multiplication- array must be of same size......corresponding element multiplication will happen
a= np.array([[1,3,4],[3,5,6],[5,68,5]])
a


array([[ 1,  3,  4],
       [ 3,  5,  6],
       [ 5, 68,  5]])

In [47]:
b=np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
a*b

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [50]:
#Comparisons

a=np.array([1,4,9,5])
b=np.array([1,6,9,4])

In [51]:
mask=(a==b)


In [52]:
a[mask]

array([1, 9])

In [53]:
np.array_equal(a,b) #it aggregates the whole array, if every element is equal then it will True else False

False

In [54]:
#logical
c=np.array([1,0,1,0])
d=np.array([1,1,1,0])
np.logical_and(c,d)

array([ True, False,  True, False])

In [55]:
np.logical_or(c,d)

array([ True,  True,  True, False])

In [56]:
#1D Array computation

a=np.array([1,4,6,8])
np.sum(a)

19

In [57]:
np.mean(a)
np.std(a)
np.median(a)
np.min(a)
np.max(a)
np.argmin(a)  # it gives the index of min element in an array
np.argmax(a)  # it gives the index of max element in an array


3

In [58]:
#2D array computation
c=np.array([[2,4,5,6],[3,5,78,5]])
c

array([[ 2,  4,  5,  6],
       [ 3,  5, 78,  5]])

In [59]:
np.sum(c,axis=0)  # when axis is set to zero it performs row wise operations

array([ 5,  9, 83, 11])

In [60]:
np.sum(c,axis=1)  #it performs column wise opeartions

array([17, 91])

In [62]:
a=np.array([True,True,False])

In [63]:
np.any(a)   #if any value in the passed argument is True then it will return a true.

True

In [64]:
np.all(a)   #if all value in the passed argument is true then it is true else it is false

False

In [69]:
#Broadcasting
type1 rows are repeated
type2 columns are repeated
type3 columns,columns are repeated

SyntaxError: invalid syntax (2497084452.py, line 2)

In [70]:
#tile function- constructs a new array by repeating array
a = np.array([4,7,9,4])
np.tile(a,(3,1))

array([[4, 7, 9, 4],
       [4, 7, 9, 4],
       [4, 7, 9, 4]])

In [71]:
b=np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
np.tile(b,(2,2))

array([[1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1.]])

In [73]:
#convert 1D array to 2D array
a=np.array([2,3,4])
b=a[0:3, np.newaxis]
b

array([[2],
       [3],
       [4]])

In [74]:
#type1 broadcasting
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6],[1,2,3]])
a
b

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [75]:
a+b

array([[2, 4, 6],
       [5, 7, 9],
       [2, 4, 6]])

In [76]:
#type2 broadcasting
c=np.array([[1],[2],[3]])
c
b

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [77]:
c

array([[1],
       [2],
       [3]])

In [78]:
b+c

array([[2, 3, 4],
       [6, 7, 8],
       [4, 5, 6]])

In [79]:
#type3 broadcasting
a

array([1, 2, 3])

In [80]:
c

array([[1],
       [2],
       [3]])

In [81]:
a+c

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [82]:
a=np.empty([4,2],dtype=np.int8)
a

array([[2, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int8)

In [84]:

a.itemsize

1

In [85]:
a=np.arange(100,200,10)
a=a.reshape(5,2)
a

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [4]:
A= np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
newArray = A[...,2]

In [22]:
newArray

array([33, 66, 99])

In [88]:
a= np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

In [89]:
a

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [32]:
b=a[::2,1::2]
b

array([[ 6, 12],
       [30, 36],
       [54, 60]])

In [91]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

c=arrayOne + arrayTwo

In [37]:
np.square(c)

array([[ 400, 1521, 1089],
       [ 625,  625,  784]])

In [41]:
a=np.arange(10,34,1)
a=a.reshape(8,3)
a

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [47]:
np.split(a,4)

[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

In [46]:
help(np.ravel)

Help on function ravel in module numpy:

ravel(a, order='C')
    Return a contiguous flattened array.
    
    A 1-D array, containing the elements of the input, is returned.  A copy is
    made only if needed.
    
    As of NumPy 1.10, the returned array will have the same type as the input
    array. (for example, a masked array will be returned for a masked array
    input)
    
    Parameters
    ----------
    a : array_like
        Input array.  The elements in `a` are read in the order specified by
        `order`, and packed as a 1-D array.
    order : {'C','F', 'A', 'K'}, optional
    
        The elements of `a` are read using this index order. 'C' means
        to index the elements in row-major, C-style order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest.  'F' means to index the elements
        in column-major, Fortran-style order, with the
        first index changing fastest, and the last index changing
       

In [51]:
s = np.array([[34,43,73],[82,22,12],[53,94,66]])
s

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [54]:
s[:,s[1,:].argsort()]

array([[73, 43, 34],
       [12, 22, 82],
       [66, 94, 53]])

In [55]:
s[:,s[:,1].argsort()]

array([[43, 34, 73],
       [22, 82, 12],
       [94, 53, 66]])

In [57]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [58]:
np.amin(sampleArray,axis=1)

array([34, 12, 53])

In [59]:
np.amin(sampleArray,axis=0)

array([34, 22, 12])

In [68]:
Array = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
Array=np.delete(Array,1,axis=1)
Array

array([[34, 73],
       [82, 12],
       [53, 66]])

In [69]:
arr = np.array([[10,10,10]])
np.insert(Array,1,arr,axis=1)

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

In [6]:
a=np.arange(10,22).reshape(3,4)
a
for i in np.nditer(a):
    print(i,end=' ')


10 11 12 13 14 15 16 17 18 19 20 21 

In [7]:
c=np.ones((10,10))
c[1:-1,1:-1]=0
c

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
c=np.diag([1,2,3,4,5])
c

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [20]:
d=np.random.random((2,3,3))
d

array([[[0.75264442, 0.6799796 , 0.26508527],
        [0.07675105, 0.22621028, 0.15925441],
        [0.0598559 , 0.27240409, 0.25082931]],

       [[0.43465322, 0.79303321, 0.46253817],
        [0.52878018, 0.14024746, 0.04746882],
        [0.4788919 , 0.3915187 , 0.55834592]]])

In [22]:
x = np.arange(16,dtype=np.int8).reshape(-1,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]], dtype=int8)

In [23]:
x[[0,-1],:]=x[[-1,0],:]
x

array([[12, 13, 14, 15],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3]], dtype=int8)